network:
  #本地监听IP
  listen_host: "192.168.8.129"
  #本地监听端口
  listen_port: "9001"
  #节点组唯一标识名称(如果节点间名称不同会找不到网络)
  rendezvous_string: "meetme"
  #网络传输流的协议id(如果节点间id不同发送不了数据)
  protocol_id: "/chain/1.1.0"
constant:
  #日志存放路径
  log_path: "./log/"
blockchain:
  #中文助记词种子路径
  chinese_mnemonic_path: "./chinese_mnemonic_world.txt"
